### ISSUE TITLE
NPM error when building with local conversejs package

### ISSUE THREAD

**Issue by ch34** [conversejs/converse-desktop#2]
I have made some changes to the conversejs library locally and wanted to use that folder for my conversejs in package.json. I have changed the package.json from **"converse.js": "^6.0.0",** to **"converse.js": "file:../conversejs",** but I am getting an error when running npm install command. I am trying to figure out whether this is the correct way for development and if it is then is there something else that needs to be modified to use a local copy of conversejs library. 

The following is the error that I see when running npm install after making the change to package.json:
$ npm install

> @converse/desktop@0.1.0 postinstall C:\Users\ch34\Git\repo\converse-desktop
> electron-builder install-app-deps

  • electron-builder version=20.44.4
  • loaded configuration file=package.json ("build" field)
Error: UNKNOWN: unknown error, lstat 'C:\Users\ch34\Git\repo\conversejs\node_modules\@converse\headless'
    at C:\Users\ch34\Git\repo\converse-desktop\node_modules\app-builder-lib\src\util\packageDependencies.ts:209:24
    at Generator.next (<anonymous>)
From previous event:
    at Collector.readChildPackage (C:\Users\ch34\Git\repo\converse-desktop\node_modules\app-builder-lib\src\util\packageDependencies.ts:206:90)
    at _bluebirdLst.default.map.it (C:\Users\ch34\Git\repo\converse-desktop\node_modules\app-builder-lib\src\util\packageDependencies.ts:191:69)
From previous event:
    at C:\Users\ch34\Git\repo\converse-desktop\node_modules\app-builder-lib\src\util\packageDependencies.ts:191:40
    at Generator.next (<anonymous>)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @converse/desktop@0.1.0 postinstall: `electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @converse/desktop@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ch34\AppData\Roaming\npm-cache\_logs\2020-12-01T22_49_26_100Z-debug.log

**Comment by nick-denry** [comment]
Hi!

Paste your full `package.json` please.

**Comment by ch34** [comment]
I resolved the issue by removing the node_modules folder from conversejs.
