### ISSUE TITLE
Windows desktop 9.1.0,login on a non-standard port

### ISSUE THREAD

**Issue by simbazavr** [conversejs/converse-desktop#26]
Where are the additional options when entering a login, for example, logging in on a non-standard port, not 5222, but, say, 15222, this is especially true when working directly from the network, thanks

**Comment by kicken** [comment]
Converse desktop only connects through either a BOSH or WebSocket endpoint, not directly to the server.  

If the correct endpoint cannot be determine automatically (via host-meta file), you enter the correct one into the connection url input and can specify a port in that URL.
