### ISSUE TITLE
Update timeframe?

### ISSUE THREAD

**Issue by licaon-kter** [conversejs/converse-desktop#3]
...version 7 is here:)

**Comment by ch34** [comment]
Is there a timeline for converse-desktop to use the version 7 of conversejs? Also, are there plans to make updates to this client in the near future?

**Comment by licaon-kter** [comment]
@ch34 https://github.com/conversejs/converse-desktop/pull/4

**Comment by ch34** [comment]
@licaon-kter Have you tested the changes made in the pull request?

**Comment by licaon-kter** [comment]
Nope, don't have a setup for that

**Comment by kicken** [comment]
I've been using it since making the PR and it's been fine for me.  I only use it for basic messaging with one person though so probably not a great test case.

It should be simple enough to build and test.  Clone my fork, checkout the branch, run `npm install` and finally run whatever dist command you need for your platform.

**Comment by ch34** [comment]
@kicken I pulled down your pull request and was able to build the project successfully. However when I did npm start, I got an error when moving the Converse window around or resizing it. Have you seem similar behavior? 
![image](https://user-images.githubusercontent.com/3502386/110019625-ae1f0680-7cf6-11eb-8e74-544868890f87.png)

**Comment by ch34** [comment]
@kicken I pulled down your pull request and was able to build the project successfully. However when I did npm start, I got an error when moving the Converse window around or resizing it. Have you seem similar behavior?
![image](https://user-images.githubusercontent.com/3502386/110019867-e9213a00-7cf6-11eb-9172-d7652ad7e3ab.png)

**Comment by kicken** [comment]
@ch34 No such problem on my end.  It seems to be a either a file permissions issue or another application locking the settings file.

Check your `%AppData%\@converse\desktop\settings.json` file and make sure it's writable, maybe just delete it and try again.

**Comment by jcbrand** [comment]
I'll make a new release of Converse Desktop together with the 9.1.0 release of Converse.
