### ISSUE TITLE
Help for compile !

### ISSUE THREAD

**Issue by nadir2021** [conversejs/converse-desktop#5]
Hi guys ! that project use a little bit old version of conversejs ! plz can you set full instructions how to compile conversejs web (https://github.com/conversejs/converse.js/) to a desktop version with electron ! iam new with electron i've tried many times but i cant do it ! 
This is my xmpp account if you want talk with me :) : nad200@404.city
(Thank you ! ).

**Comment by jcbrand** [comment]
If you'd like to use Converse Desktop with the latest version of Converse, you can do the following (on Linux/MacOS):

```
# Check out converse.js, build it and then use "npm link" to create a symlink
git clone git@github.com:conversejs/converse.js.git
cd converse.js
npm link
make dev # This creates builds in ./dist/ from the latest code

# Check out converse desktop and use "npm link" to link your checkout of converse.js into its node_modules
git clone git@github.com:conversejs/converse-desktop.git
cd converse-desktop
npm link converse.js # this links your converse.js checkout into this repo's node_modules
make serve
```
