### ISSUE TITLE
Compilation Errors Ubuntu 20.04

### ISSUE THREAD

**Issue by raphael10-collab** [conversejs/converse-desktop#6]
raphy@pc:~/Downloads$ git clone https://github.com/conversejs/converse-desktop.git
    Cloning into 'converse-desktop'...
    remote: Enumerating objects: 701, done.
    remote: Counting objects: 100% (701/701), done.
    remote: Compressing objects: 100% (304/304), done.
    remote: Total 701 (delta 385), reused 666 (delta 354), pack-reused 0
    Receiving objects: 100% (701/701), 568.54 KiB | 5.63 MiB/s, done.
    Resolving deltas: 100% (385/385), done.
    raphy@pc:~/Downloads$ cd converse-desktop/
    raphy@pc:~/Downloads/converse-desktop$ npm i
    raphy@pc:~/Downloads/converse-desktop$ npm i
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm ERR! code 1
    npm ERR! path /home/raphy/Downloads/converse-desktop/node_modules/keytar
    npm ERR! command failed
    npm ERR! command sh -c prebuild-install || node-gyp rebuild
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@6.1.0
    npm ERR! gyp info using node@14.17.0 | linux | x64
    npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/keytar/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/.cache/node-gyp/14.17.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/raphy/.cache/node-gyp/14.17.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/raphy/Downloads/converse-desktop/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/raphy/.cache/node-gyp/14.17.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/raphy/Downloads/converse-desktop/node_modules/keytar',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! Package libsecret-1 was not found in the pkg-config search path.
    npm ERR! Perhaps you should add the directory containing `libsecret-1.pc'
    npm ERR! to the PKG_CONFIG_PATH environment variable
    npm ERR! No package 'libsecret-1' found
    npm ERR! gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    npm ERR! gyp ERR! configure error 
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/lib/configure.js:351:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    npm ERR! gyp ERR! System Linux 5.8.0-53-generic
    npm ERR! gyp ERR! command "/home/raphy/.nvm/versions/node/v14.17.0/bin/node" "/home/raphy/Downloads/converse-desktop/node_modules/.bin/node-gyp" "rebuild"
    npm ERR! gyp ERR! cwd /home/raphy/Downloads/converse-desktop/node_modules/keytar
    npm ERR! gyp ERR! node -v v14.17.0
    npm ERR! gyp ERR! node-gyp -v v6.1.0
    npm ERR! gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/raphy/.npm/_logs/2021-05-29T09_39_06_114Z-debug.log
raphy@pc:~/Downloads/converse-desktop$

**Comment by nick-denry** [comment]
Hi! Please try this https://github.com/nodejs/node-gyp/issues/2273#issuecomment-738548377

**Comment by raphael10-collab** [comment]
raphy@pc:~$ npm install --global node-gyp@latest
    
    changed 91 packages, and audited 92 packages in 3s
    
    3 packages are looking for funding
      run `npm fund` for details
    
    found 0 vulnerabilities
    raphy@pc:~$ npm config set node_gyp $(npm prefix -g)/lib/node_modules/node-gyp/bin/node-gyp.js
    raphy@pc:~$ python3 --version
    Python 3.8.5
    raphy@pc:~$ python3 -m pip --version
    pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
    raphy@pc:~$ cd Downloads/
    raphy@pc:~/Downloads$ git clone https://github.com/conversejs/converse-desktop.git
    Cloning into 'converse-desktop'...
    remote: Enumerating objects: 701, done.
    remote: Counting objects: 100% (701/701), done.
    remote: Compressing objects: 100% (304/304), done.
    remote: Total 701 (delta 385), reused 666 (delta 354), pack-reused 0
    Receiving objects: 100% (701/701), 568.54 KiB | 12.10 MiB/s, done.
    Resolving deltas: 100% (385/385), done.
    raphy@pc:~/Downloads$ cd converse-desktop/
    raphy@pc:~/Downloads/converse-desktop$ npm i
    raphy@pc:~/Downloads/converse-desktop$ npm i
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm ERR! code 1
    npm ERR! path /home/raphy/Downloads/converse-desktop/node_modules/keytar
    npm ERR! command failed
    npm ERR! command sh -c prebuild-install || node-gyp rebuild
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@6.1.0
    npm ERR! gyp info using node@14.17.0 | linux | x64
    npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/keytar/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/.cache/node-gyp/14.17.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/raphy/.cache/node-gyp/14.17.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/raphy/Downloads/converse-desktop/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/raphy/.cache/node-gyp/14.17.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/raphy/Downloads/converse-desktop/node_modules/keytar',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! Package libsecret-1 was not found in the pkg-config search path.
    npm ERR! Perhaps you should add the directory containing `libsecret-1.pc'
    npm ERR! to the PKG_CONFIG_PATH environment variable
    npm ERR! No package 'libsecret-1' found
    npm ERR! gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    npm ERR! gyp ERR! configure error 
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/lib/configure.js:351:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    npm ERR! gyp ERR! System Linux 5.8.0-53-generic
    npm ERR! gyp ERR! command "/home/raphy/.nvm/versions/node/v14.17.0/bin/node" "/home/raphy/Downloads/converse-desktop/node_modules/.bin/node-gyp" "rebuild"
    npm ERR! gyp ERR! cwd /home/raphy/Downloads/converse-desktop/node_modules/keytar
    npm ERR! gyp ERR! node -v v14.17.0
    npm ERR! gyp ERR! node-gyp -v v6.1.0
    npm ERR! gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/raphy/.npm/_logs/2021-05-31T05_48_02_755Z-debug.log
    raphy@pc:~/Downloads/converse-desktop$

**Comment by licaon-kter** [comment]
Install libsecret?

**Comment by raphael10-collab** [comment]
raphy@pc:~$ sudo apt-get install -y libsecret-tools
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following NEW packages will be installed:
      libsecret-tools
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 10,3 kB of archives.
    After this operation, 44,0 kB of additional disk space will be used.
    Get:1 http://it.archive.ubuntu.com/ubuntu focal-updates/universe amd64 libsecret-tools amd64 0.20.3-0ubuntu1 [10,3 kB]
    Fetched 10,3 kB in 0s (122 kB/s)            
    Selecting previously unselected package libsecret-tools.
    dpkg: warning: files list file for package 'droidcam' missing; assuming package has no files currently installed
    (Reading database ... 230210 files and directories currently installed.)
    Preparing to unpack .../libsecret-tools_0.20.3-0ubuntu1_amd64.deb ...
    Unpacking libsecret-tools (0.20.3-0ubuntu1) ...
    Setting up libsecret-tools (0.20.3-0ubuntu1) ...
    Processing triggers for man-db (2.9.1-1) ...
    raphy@pc:~$ npm config set node_gyp $(npm prefix -g)/lib/node_modules/node-gyp/bin/node-gyp.js
    raphy@pc:~/Downloads/converse-desktop$ npm i
    npm WARN deprecated har-validator@5.1.5: this library is no longer supported
    npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm ERR! code 1
    npm ERR! path /home/raphy/Downloads/converse-desktop/node_modules/keytar
    npm ERR! command failed
    npm ERR! command sh -c prebuild-install || node-gyp rebuild
    npm ERR! gyp info it worked if it ends with ok
    npm ERR! gyp info using node-gyp@6.1.0
    npm ERR! gyp info using node@14.17.0 | linux | x64
    npm ERR! gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
    npm ERR! gyp info spawn /usr/bin/python3
    npm ERR! gyp info spawn args [
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/gyp/gyp_main.py',
    npm ERR! gyp info spawn args   'binding.gyp',
    npm ERR! gyp info spawn args   '-f',
    npm ERR! gyp info spawn args   'make',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/keytar/build/config.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/addon.gypi',
    npm ERR! gyp info spawn args   '-I',
    npm ERR! gyp info spawn args   '/home/raphy/.cache/node-gyp/14.17.0/include/node/common.gypi',
    npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
    npm ERR! gyp info spawn args   '-Dvisibility=default',
    npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/raphy/.cache/node-gyp/14.17.0',
    npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/raphy/Downloads/converse-desktop/node_modules/node-gyp',
    npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/raphy/.cache/node-gyp/14.17.0/<(target_arch)/node.lib',
    npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/raphy/Downloads/converse-desktop/node_modules/keytar',
    npm ERR! gyp info spawn args   '-Dnode_engine=v8',
    npm ERR! gyp info spawn args   '--depth=.',
    npm ERR! gyp info spawn args   '--no-parallel',
    npm ERR! gyp info spawn args   '--generator-output',
    npm ERR! gyp info spawn args   'build',
    npm ERR! gyp info spawn args   '-Goutput_dir=.'
    npm ERR! gyp info spawn args ]
    npm ERR! Package libsecret-1 was not found in the pkg-config search path.
    npm ERR! Perhaps you should add the directory containing `libsecret-1.pc'
    npm ERR! to the PKG_CONFIG_PATH environment variable
    npm ERR! No package 'libsecret-1' found
    npm ERR! gyp: Call to 'pkg-config --cflags libsecret-1' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
    npm ERR! gyp ERR! configure error 
    npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
    npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/raphy/Downloads/converse-desktop/node_modules/node-gyp/lib/configure.js:351:16)
    npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
    npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    npm ERR! gyp ERR! System Linux 5.8.0-53-generic
    npm ERR! gyp ERR! command "/home/raphy/.nvm/versions/node/v14.17.0/bin/node" "/home/raphy/Downloads/converse-desktop/node_modules/.bin/node-gyp" "rebuild"
    npm ERR! gyp ERR! cwd /home/raphy/Downloads/converse-desktop/node_modules/keytar
    npm ERR! gyp ERR! node -v v14.17.0
    npm ERR! gyp ERR! node-gyp -v v6.1.0
    npm ERR! gyp ERR! not ok
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/raphy/.npm/_logs/2021-05-31T07_40_17_049Z-debug.log

**Comment by licaon-kter** [comment]
You can use packages.ubuntu.com to search for package contents, you'd find that you need to install `libsecret-1-dev` instead.
